FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Gateway/EkgAnalysisPlatform.ApiGateway/EkgAnalysisPlatform.ApiGateway.csproj", "Gateway/EkgAnalysisPlatform.ApiGateway/"]
COPY ["BuildingBlocks/EventBus/EkgAnalysisPlatform.BuildingBlocks.EventBus/EkgAnalysisPlatform.BuildingBlocks.EventBus.csproj", "BuildingBlocks/EventBus/EkgAnalysisPlatform.BuildingBlocks.EventBus/"]
COPY ["BuildingBlocks/Common/EkgAnalysisPlatform.BuildingBlocks.Common/EkgAnalysisPlatform.BuildingBlocks.Common.csproj", "BuildingBlocks/Common/EkgAnalysisPlatform.BuildingBlocks.Common/"]
RUN dotnet restore "Gateway/EkgAnalysisPlatform.ApiGateway/EkgAnalysisPlatform.ApiGateway.csproj"
COPY . .
WORKDIR "/src/Gateway/EkgAnalysisPlatform.ApiGateway"
RUN dotnet build "EkgAnalysisPlatform.ApiGateway.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "EkgAnalysisPlatform.ApiGateway.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "EkgAnalysisPlatform.ApiGateway.dll"]