FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Services/PatientService/EkgAnalysisPlatform.PatientService.API/EkgAnalysisPlatform.PatientService.API.csproj", "Services/PatientService/EkgAnalysisPlatform.PatientService.API/"]
COPY ["Services/PatientService/EkgAnalysisPlatform.PatientService.Domain/EkgAnalysisPlatform.PatientService.Domain.csproj", "Services/PatientService/EkgAnalysisPlatform.PatientService.Domain/"]
COPY ["Services/PatientService/EkgAnalysisPlatform.PatientService.Infrastructure/EkgAnalysisPlatform.PatientService.Infrastructure.csproj", "Services/PatientService/EkgAnalysisPlatform.PatientService.Infrastructure/"]
COPY ["BuildingBlocks/EventBus/EkgAnalysisPlatform.BuildingBlocks.EventBus/EkgAnalysisPlatform.BuildingBlocks.EventBus.csproj", "BuildingBlocks/EventBus/EkgAnalysisPlatform.BuildingBlocks.EventBus/"]
COPY ["BuildingBlocks/Common/EkgAnalysisPlatform.BuildingBlocks.Common/EkgAnalysisPlatform.BuildingBlocks.Common.csproj", "BuildingBlocks/Common/EkgAnalysisPlatform.BuildingBlocks.Common/"]
RUN dotnet restore "Services/PatientService/EkgAnalysisPlatform.PatientService.API/EkgAnalysisPlatform.PatientService.API.csproj"
COPY . .
WORKDIR "/src/Services/PatientService/EkgAnalysisPlatform.PatientService.API"
RUN dotnet build "EkgAnalysisPlatform.PatientService.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "EkgAnalysisPlatform.PatientService.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "EkgAnalysisPlatform.PatientService.API.dll"]