FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Services/BatchProcessingService/EkgAnalysisPlatform.BatchProcessingService.API/EkgAnalysisPlatform.BatchProcessingService.API.csproj", "Services/BatchProcessingService/EkgAnalysisPlatform.BatchProcessingService.API/"]
COPY ["Services/BatchProcessingService/EkgAnalysisPlatform.BatchProcessingService.Domain/EkgAnalysisPlatform.BatchProcessingService.Domain.csproj", "Services/BatchProcessingService/EkgAnalysisPlatform.BatchProcessingService.Domain/"]
COPY ["Services/BatchProcessingService/EkgAnalysisPlatform.BatchProcessingService.Infrastructure/EkgAnalysisPlatform.BatchProcessingService.Infrastructure.csproj", "Services/BatchProcessingService/EkgAnalysisPlatform.BatchProcessingService.Infrastructure/"]
COPY ["BuildingBlocks/EventBus/EkgAnalysisPlatform.BuildingBlocks.EventBus/EkgAnalysisPlatform.BuildingBlocks.EventBus.csproj", "BuildingBlocks/EventBus/EkgAnalysisPlatform.BuildingBlocks.EventBus/"]
COPY ["BuildingBlocks/Common/EkgAnalysisPlatform.BuildingBlocks.Common/EkgAnalysisPlatform.BuildingBlocks.Common.csproj", "BuildingBlocks/Common/EkgAnalysisPlatform.BuildingBlocks.Common/"]
RUN dotnet restore "Services/BatchProcessingService/EkgAnalysisPlatform.BatchProcessingService.API/EkgAnalysisPlatform.BatchProcessingService.API.csproj"
COPY . .
WORKDIR "/src/Services/BatchProcessingService/EkgAnalysisPlatform.BatchProcessingService.API"
RUN dotnet build "EkgAnalysisPlatform.BatchProcessingService.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "EkgAnalysisPlatform.BatchProcessingService.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
RUN mkdir -p /app/data
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "EkgAnalysisPlatform.BatchProcessingService.API.dll"]