services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ekg-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  patient-service:
    build:
      context: .
      dockerfile: Services/PatientService/EkgAnalysisPlatform.PatientService.API/Dockerfile
    container_name: ekg-patient-service
    ports:
      - "5055:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__PatientDatabase=Data Source=/app/data/patient.db
      - EventBus__HostName=rabbitmq
    volumes:
      - patient_data:/app/data
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  ekg-signal-service:
    build:
      context: .
      dockerfile: Services/EkgSignalService/EkgAnalysisPlatform.EkgSignalService.API/Dockerfile
    container_name: ekg-signal-service
    ports:
      - "5125:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__EkgSignalDatabase=Data Source=/app/data/ekgsignal.db
      - EventBus__HostName=rabbitmq
    volumes:
      - ekgsignal_data:/app/data
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  analysis-service:
    build:
      context: .
      dockerfile: Services/AnalysisService/EkgAnalysisPlatform.AnalysisService.API/Dockerfile
    container_name: ekg-analysis-service
    ports:
      - "5246:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__AnalysisDatabase=Data Source=/app/data/analysis.db
      - EventBus__HostName=rabbitmq
    volumes:
      - analysis_data:/app/data
    depends_on:
      rabbitmq:
        condition: service_healthy
      ekg-signal-service:
        condition: service_started
    restart: unless-stopped

  batch-processing-service:
    build:
      context: .
      dockerfile: Services/BatchProcessingService/EkgAnalysisPlatform.BatchProcessingService.API/Dockerfile
    container_name: ekg-batch-processing-service
    ports:
      - "5181:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__BatchDatabase=Data Source=/app/data/batch.db
      - EventBus__HostName=rabbitmq
    volumes:
      - batch_data:/app/data
    depends_on:
      rabbitmq:
        condition: service_healthy
      ekg-signal-service:
        condition: service_started
      analysis-service:
        condition: service_started
    restart: unless-stopped

  api-gateway:
    build:
      context: .
      dockerfile: Gateway/EkgAnalysisPlatform.ApiGateway/Dockerfile
    container_name: ekg-api-gateway
    ports:
      - "5279:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EventBus__HostName=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
      patient-service:
        condition: service_started
      ekg-signal-service:
        condition: service_started
      analysis-service:
        condition: service_started
      batch-processing-service:
        condition: service_started
    restart: unless-stopped

volumes:
  rabbitmq_data:
  patient_data:
  ekgsignal_data:
  analysis_data:
  batch_data: