FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Services/EkgSignalService/EkgAnalysisPlatform.EkgSignalService.API/EkgAnalysisPlatform.EkgSignalService.API.csproj", "Services/EkgSignalService/EkgAnalysisPlatform.EkgSignalService.API/"]
COPY ["Services/EkgSignalService/EkgAnalysisPlatform.EkgSignalService.Domain/EkgAnalysisPlatform.EkgSignalService.Domain.csproj", "Services/EkgSignalService/EkgAnalysisPlatform.EkgSignalService.Domain/"]
COPY ["Services/EkgSignalService/EkgAnalysisPlatform.EkgSignalService.Infrastructure/EkgAnalysisPlatform.EkgSignalService.Infrastructure.csproj", "Services/EkgSignalService/EkgAnalysisPlatform.EkgSignalService.Infrastructure/"]
COPY ["BuildingBlocks/EventBus/EkgAnalysisPlatform.BuildingBlocks.EventBus/EkgAnalysisPlatform.BuildingBlocks.EventBus.csproj", "BuildingBlocks/EventBus/EkgAnalysisPlatform.BuildingBlocks.EventBus/"]
COPY ["BuildingBlocks/Common/EkgAnalysisPlatform.BuildingBlocks.Common/EkgAnalysisPlatform.BuildingBlocks.Common.csproj", "BuildingBlocks/Common/EkgAnalysisPlatform.BuildingBlocks.Common/"]
RUN dotnet restore "Services/EkgSignalService/EkgAnalysisPlatform.EkgSignalService.API/EkgAnalysisPlatform.EkgSignalService.API.csproj"
COPY . .
WORKDIR "/src/Services/EkgSignalService/EkgAnalysisPlatform.EkgSignalService.API"
RUN dotnet build "EkgAnalysisPlatform.EkgSignalService.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "EkgAnalysisPlatform.EkgSignalService.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
RUN mkdir -p /app/data
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "EkgAnalysisPlatform.EkgSignalService.API.dll"]